In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
#creating an array

In [5]:
x=np.array([[1,2,3],[4,5,7]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 7]])

In [7]:
np.shape(x)

(2, 3)

In [8]:
np.size(x)

6

In [10]:
np.ndim(x)

2

In [12]:
x.itemsize

4

In [13]:
#reshape

In [14]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 7]])

In [16]:
x.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [7]])

In [17]:
#slicing

In [18]:
x[0]

array([1, 2, 3])

In [19]:
x[:1]

array([[1, 2, 3]])

In [20]:
x[:2]

array([[1, 2, 3],
       [4, 5, 7]])

In [21]:
x[0,1]

2

In [22]:
x[0,0]

1

In [23]:
x[1,1]

5

In [24]:
x[1,2]

7

In [28]:
x[0:,0]

array([1, 4])

In [29]:
x[:,0]

array([1, 4])

In [30]:
x[:,-1]

array([3, 7])

In [35]:
x[:,0::2]

array([[1, 3],
       [4, 7]])

In [36]:
x[:,0:2]

array([[1, 2],
       [4, 5]])

In [37]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
#row accesing

In [40]:
a[0,2]

3

In [43]:
a[0:1]

array([[1, 2, 3]])

In [48]:
a[0:,1]

array([2, 5, 8])

# 

In [49]:
a[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [50]:
a[:,0:1]

array([[1],
       [4],
       [7]])

In [51]:
a[:,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a[1,:]

array([4, 5, 6])

In [58]:
a.max()

9

In [59]:
a.sum()

45

In [60]:
x.mean()

3.6666666666666665

In [62]:
#axis=1(row),axis=0(col)
a.min(axis=0)

array([1, 2, 3])

a.min(axis=1)

In [63]:
a.min(axis=1)

array([1, 4, 7])

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
a.sum(axis=1)

array([ 6, 15, 24])

In [66]:
x.sum(axis=0)

array([ 5,  7, 10])

In [67]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [68]:
np.std(a)

2.581988897471611

In [69]:
b=np.array([[1,3,5],[6,8,4],[3,7,2]])

In [70]:
b

array([[1, 3, 5],
       [6, 8, 4],
       [3, 7, 2]])

In [72]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 3, 5],
       [6, 8, 4],
       [3, 7, 2]])

In [73]:
np.hstack((a,b))

array([[1, 2, 3, 1, 3, 5],
       [4, 5, 6, 6, 8, 4],
       [7, 8, 9, 3, 7, 2]])

In [74]:
np.ravel((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 5, 6, 8, 4, 3, 7, 2])

In [75]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
for i in np.arange(1,5):
    print(x)

[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]
[[1 2 3]
 [4 5 7]]


In [77]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427,  0.6569866 ]])

In [78]:
np.tan(x)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501,  0.87144798]])

In [79]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [80]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [82]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

## pandas
#### slicing and dataframe
#### merging and joining
#### concatenation
#### changing the index 
#### change coloumn header
#### data munging

In [83]:
import pandas as pd

In [84]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [85]:
# creating a series data type

In [87]:
s=pd.Series([1,2,3,34,5,56])

In [88]:
s

0     1
1     2
2     3
3    34
4     5
5    56
dtype: int64

In [90]:
s=pd.Series([1,2,3,34,5,56],index=['x','y','z','a','b','c'])
s

x     1
y     2
z     3
a    34
b     5
c    56
dtype: int64

In [98]:
v1=[1,2,3,4]
v2=[5,6,7,8]
df=pd.DataFrame({'x':v1,'y':v2})

In [99]:
df

x  y
0  1  5
1  2  6
2  3  7
3  4  8

In [100]:
df.isnull()

x      y
0  False  False
1  False  False
2  False  False
3  False  False

In [102]:
df1=pd.DataFrame({'x':[20,32,34,21],'y':[6,4,3,299]})
df1

x    y
0  20    6
1  32    4
2  34    3
3  21  299

In [107]:
df1=pd.DataFrame({'x':[20,32,34,21],'y':[6,4,3,299]},index=['a','b','c','d'],dtype=float)

In [108]:
df1

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [110]:
df1.size

8

In [111]:
df1.values

array([[ 20.,   6.],
       [ 32.,   4.],
       [ 34.,   3.],
       [ 21., 299.]])

In [112]:
df1.shape

(4, 2)

In [114]:
df1.isnull()

x      y
a  False  False
b  False  False
c  False  False
d  False  False

## slicing

In [116]:
df1.head()

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [119]:
df1.tail(2)

x      y
c  34.0    3.0
d  21.0  299.0

### mearging and joning

In [120]:
df1

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [121]:
df

x  y
0  1  5
1  2  6
2  3  7
3  4  8

In [122]:
print(pd.merge(df,df1))

Empty DataFrame
Columns: [x, y]
Index: []


In [123]:
df2=pd.DataFrame({'x':[50,45,84,67],'y':[36,46,39,29]},index=['a','b','c','d'],dtype=float)

In [124]:
df2

x     y
a  50.0  36.0
b  45.0  46.0
c  84.0  39.0
d  67.0  29.0

In [125]:
print(pd.merge(df1,df2))

Empty DataFrame
Columns: [x, y]
Index: []


In [129]:
m=pd.merge(df1,df2)

In [131]:
m

Empty DataFrame
Columns: [x, y]
Index: []

In [133]:
df3=pd.DataFrame({'x':[20,32,34,21],'y':[6,4,3,299]},index=['a','b','c','d'],dtype=float)

In [134]:
df3

x      y
a  20.0    6.0
b  32.0    4.0
c  34.0    3.0
d  21.0  299.0

In [135]:
pd.merge(df1,df3)

x      y
0  20.0    6.0
1  32.0    4.0
2  34.0    3.0
3  21.0  299.0

In [147]:
d=[[3,4,5],[6,7,5,8],[8,2,9]]
f2=pd.DataFrame(d,columns=['x','y','z','z1'],index=['a','b','c'])

In [152]:
f3=pd.DataFrame({'name':[6,8,77],'gender':[1,0,1]})

In [154]:
j=f2.join(f3)

In [155]:
j

x  y  z   z1  name  gender
a  3  4  5  NaN   NaN     NaN
b  6  7  5  8.0   NaN     NaN
c  8  2  9  NaN   NaN     NaN

In [158]:
j.notnull()

x     y     z     z1   name  gender
a  True  True  True  False  False   False
b  True  True  True   True  False   False
c  True  True  True  False  False   False

In [159]:
j.isnull()

x      y      z     z1  name  gender
a  False  False  False   True  True    True
b  False  False  False  False  True    True
c  False  False  False   True  True    True

In [169]:
## index changing
c1=pd.DataFrame({1:[1,2,3],2:[4,5,6],'i':['x','y','z']})
c1.set_index('i')

1  2
i      
x  1  4
y  2  5
z  3  6

In [170]:
#changing the column headers
c2=c1.rename(columns={1:'a',2:'b'})
c2

a  b  i
0  1  4  x
1  2  5  y
2  3  6  z

In [173]:
# data munging
dd=pd.read_csv("table.csv")

In [174]:
dd

x  y   z
0  5  6  10
1  1  9   4
2  3  0   7

In [176]:
dd1=pd.read_json("rose.png")

ValueError: Expected object or value